-- Doctor invitations (Admin ADM-003) and their history (p.113e)

CREATE TABLE invitation (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_name          VARCHAR(50),
    email                VARCHAR(100),
    mobile               VARCHAR(13),
    mobile_search_digits VARCHAR(7),
    status               VARCHAR(10)              NOT NULL,
    issued_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    reissue_count        INT                      NOT NULL DEFAULT 0,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_invitation_status CHECK (status IN ('PENDING', 'USED', 'EXPIRED', 'REVOKED'))
);

CREATE INDEX ix_invitation_status_expires ON invitation (status, expires_at);
CREATE INDEX ix_invitation_email_status ON invitation (email, status);
CREATE INDEX ix_invitation_created ON invitation (created_at DESC, id DESC);

CREATE TABLE invitation_history (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invitation_id BIGINT                   NOT NULL REFERENCES invitation (id),
    action        VARCHAR(10)              NOT NULL,
    actor         VARCHAR(100),
    occurred_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_history_action CHECK (action IN ('ISSUED', 'REISSUED', 'EDITED', 'REVOKED', 'USED', 'EXPIRED'))
);

CREATE INDEX ix_history_invitation ON invitation_history (invitation_id, occurred_at);
